---
- name: Deploy Web Application
  hosts: localhost
  connection: local

- name: Install Docker on Amazon Linux
  hosts: localhost
  become: yes

  tasks:
    - name: Install Docker package
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Create a Docker image
      docker_image:
        name: mytask:2.0
        source: build
        build:
          path: .
    - name: Run the web app container
      docker_container:
        name: container-webapp
        image: mytask:2.0
        state: started
        exposed_ports:
          - "3300"
        published_ports:
          - "3300:3300"
