name: CI/CD Pipeline for webapplication

on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ami-0614680123427b75e

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run Unit Tests
      run: | 
        npm test
        echo "Tests run successfully"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
         docker build -t mytask:3.0 -f Dockerfile

  deploy:
    runs-on: ami-0614680123427b75e
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ansible
      uses: wingrunr21/setup-ansible@v2

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i /home/ec2-user/WebApplication/Ansible/MyNodeApp/webapp.js/Inventoryfile deploy.yml
