name: CI/CD Pipeline for webapplication

on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Debug Current Directory
      run: |
        pwd
        ls -al

    - name: Install dependencies
      run: |
        cd webapp  
        npm install

    - name: Run Unit Tests
      run: | 
        cd webapp
        npm test
        echo "Tests run successfully"

    - name: Build Docker Image
      run: |
        cd webapp
        docker build -t mytask:3.0 -f Dockerfile .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ansible
      uses: wingrunr21/setup-ansible@v2

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i /home/ec2-user/WebApplication/Ansible/MyNodeApp/webapp.js/Inventoryfile deploy.yml
